#!/usr/bin/env python3
"""
Translate a batch of strings for a specific language.
Usage: python3 translate_batch.py <lang_code> <chunk_number>

Reads from i18n/translations/{lang}_missing.json
Writes to i18n/translations/{lang}_chunk_{n}.json
"""
import json
import sys
import os

# This script is called by the build system.
# The actual translations are generated by AI and saved as JSON files.
# This is a helper to merge chunk files into the main translation cache.

def merge_chunks(lang_code):
    """Merge all chunk files into the main translation cache."""
    trans_dir = os.path.dirname(os.path.abspath(__file__)) + "/translations"
    
    # Load existing cache
    cache_file = os.path.join(trans_dir, f"{lang_code}.json")
    cache = {}
    if os.path.exists(cache_file):
        with open(cache_file) as f:
            cache = json.load(f)
    
    # Find and merge chunk files
    merged = 0
    for fname in sorted(os.listdir(trans_dir)):
        if fname.startswith(f"{lang_code}_chunk_") and fname.endswith(".json"):
            chunk_file = os.path.join(trans_dir, fname)
            with open(chunk_file) as f:
                chunk = json.load(f)
            cache.update(chunk)
            merged += len(chunk)
            # Clean up chunk file
            os.remove(chunk_file)
    
    # Save merged cache
    with open(cache_file, 'w', encoding='utf-8') as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)
    
    print(f"{lang_code}: merged {merged} translations into cache ({len(cache)} total)")
    return cache


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 translate_batch.py <lang_code> [merge]")
        sys.exit(1)
    
    lang = sys.argv[1]
    merge_chunks(lang)
